// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzqczjxlppbmrccwwsoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6cWN6anhscHBibXJjY3d3c296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NzkzMTIsImV4cCI6MjA2MDU1NTMxMn0.zmPMFFzc62CF_s4RHwhmg8cdF7srcTb440XkDj4qGPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);